import { id } from "zod/v4/locales"

export const dummyListings = [
  {
    id: 1,
    title: "E-commerce Store",
    description:
      "Established Shopify store selling premium kitchenware with a loyal customer base and growing monthly sales.",
    price: 1200,
    niche: "E-commerce",
    revenueGenerating: true,
    location: "India",
    targetCountry: "United States",
    businessAge: 4,
    monthlyRevenue: 897082,
    monthlyProfit: 147082,
    monthlyPageviews: 50000,
    revenueMultiple: 5.5,
    profitMultiple: 1,
    netProfit: 1764985,
    revenue: 10764985,
    image: "/service.png",
  },
  {
    id: 2,
    title: "SaaS Marketing Platform",
    description: "B2B SaaS platform helping small businesses automate their marketing campaigns with minimal setup.",
    price: 4500,
    niche: "SaaS",
    revenueGenerating: true,
    location: "United States",
    targetCountry: "Global",
    businessAge: 2,
    monthlyRevenue: 1250000,
    monthlyProfit: 750000,
    monthlyPageviews: 35000,
    revenueMultiple: 6.2,
    profitMultiple: 3.5,
    netProfit: 9000000,
    revenue: 15000000,
    image: "/service.png",
  },
  {
    id: 3,
    title: "Content Blog",
    description:
      "Established blog in the fitness niche with over 200 articles and monetized through affiliate marketing and ads.",
    price: 850,
    niche: "Content",
    revenueGenerating: true,
    location: "United Kingdom",
    targetCountry: "United States",
    businessAge: 3,
    monthlyRevenue: 350000,
    monthlyProfit: 320000,
    monthlyPageviews: 120000,
    revenueMultiple: 4.8,
    profitMultiple: 2.2,
    netProfit: 3840000,
    revenue: 4200000,
    image: "/service.png",
  },
  {
    id: 4,
    title: "Dropshipping Store",
    description: "Fully automated dropshipping store in the pet niche with supplier relationships already established.",
    price: 1000,
    niche: "E-commerce",
    revenueGenerating: true,
    location: "Canada",
    targetCountry: "United States",
    businessAge: 8,
    monthlyRevenue: 450000,
    monthlyProfit: 120000,
    monthlyPageviews: 25000,
    revenueMultiple: 3.8,
    profitMultiple: 1.8,
    netProfit: 1440000,
    revenue: 5400000,
    image: "/service.png",
  },
  {
    id: 5,
    title: "Mobile App",
    description:
      "Productivity app with 50,000+ downloads and subscription-based revenue model with high retention rate.",
    price: 7500,
    niche: "SaaS",
    revenueGenerating: true,
    location: "Germany",
    targetCountry: "Europe",
    businessAge: 12,
    monthlyRevenue: 1800000,
    monthlyProfit: 1200000,
    monthlyPageviews: 0,
    revenueMultiple: 7.5,
    profitMultiple: 4.2,
    netProfit: 14400000,
    revenue: 21600000,
    image: "/service.png",
  },
  {
    id: 6,
    title: "Amazon FBA Business",
    description: "Profitable Amazon FBA business selling kitchen gadgets with 15 SKUs and excellent customer reviews.",
    price: 3200,
    niche: "E-commerce",
    revenueGenerating: true,
    location: "Australia",
    targetCountry: "United States",
    businessAge: 13,
    monthlyRevenue: 980000,
    monthlyProfit: 390000,
    monthlyPageviews: 0,
    revenueMultiple: 4.2,
    profitMultiple: 2.5,
    netProfit: 4680000,
    revenue: 11760000,
    image: "/service.png",
  },
  {
    id: 7,
    title: "Membership Site",
    description: "Premium membership site in the photography niche with 500+ active members and recurring revenue.",
    price: 2800,
    niche: "Content",
    revenueGenerating: true,
    location: "United States",
    targetCountry: "Global",
    businessAge: 15,
    monthlyRevenue: 750000,
    monthlyProfit: 600000,
    monthlyPageviews: 45000,
    revenueMultiple: 5.8,
    profitMultiple: 3.2,
    netProfit: 7200000,
    revenue: 9000000,
    image: "/service.png",
  },
  {
    id: 8,
    title: "Print on Demand Store",
    description:
      "Established print on demand store with unique designs in the pet lover niche and growing social media presence.",
    price: 1500,
    niche: "E-commerce",
    revenueGenerating: true,
    location: "France",
    targetCountry: "Europe",
    businessAge: 2,
    monthlyRevenue: 520000,
    monthlyProfit: 210000,
    monthlyPageviews: 30000,
    revenueMultiple: 4.5,
    profitMultiple: 2.8,
    netProfit: 2520000,
    revenue: 6240000,
    image: "/service.png",
  },
  {
    id: 9,
    title: "Digital Product Store",
    description:
      "Online store selling digital products in the education niche with automated delivery and minimal maintenance.",
    price: 2200,
    niche: "Digital Products",
    revenueGenerating: true,
    location: "Spain",
    targetCountry: "Global",
    businessAge: 3,
    monthlyRevenue: 680000,
    monthlyProfit: 580000,
    monthlyPageviews: 40000,
    revenueMultiple: 5.2,
    profitMultiple: 3.1,
    netProfit: 6960000,
    revenue: 8160000,
    image: "/service.png",
  },
  {
    id: 10,
    title: "Lead Generation Website",
    description:
      "Lead generation website in the home services industry with established client relationships and recurring revenue.",
    price: 900,
    niche: "Lead Gen",
    revenueGenerating: true,
    location: "United States",
    targetCountry: "United States",
    businessAge: 14,
    monthlyRevenue: 950000,
    monthlyProfit: 780000,
    monthlyPageviews: 25000,
    revenueMultiple: 6.0,
    profitMultiple: 3.5,
    netProfit: 9360000,
    revenue: 11400000,
    image: "/service.png",
  },
  {
    id: 11,
    title: "Affiliate Marketing Blog",
    description:
      "Established blog in the travel niche with high-converting affiliate content and diverse traffic sources.",
    price: 800,
    niche: "Content",
    revenueGenerating: true,
    location: "Italy",
    targetCountry: "Europe",
    businessAge: 3,
    monthlyRevenue: 580000,
    monthlyProfit: 520000,
    monthlyPageviews: 85000,
    revenueMultiple: 4.8,
    profitMultiple: 2.9,
    netProfit: 6240000,
    revenue: 6960000,
    image: "/service.png",
  },
  {
    id: 12,
    title: "Online Course Platform",
    description:
      "Platform with 15 courses in the business niche with established instructor relationships and growing student base.",
    price: 5000,
    niche: "Education",
    revenueGenerating: true,
    location: "Canada",
    targetCountry: "Global",
    businessAge: 2,
    monthlyRevenue: 1350000,
    monthlyProfit: 980000,
    monthlyPageviews: 60000,
    revenueMultiple: 6.5,
    profitMultiple: 3.8,
    netProfit: 11760000,
    revenue: 16200000,
    image: "/service.png",
  },
  {
    id: 13,
    title: "Software Tool",
    description: "Desktop software tool for video editing with lifetime licenses and established customer base.",
    price: 650,
    niche: "SaaS",
    revenueGenerating: true,
    location: "United States",
    targetCountry: "Global",
    businessAge: 5,
    monthlyRevenue: 1580000,
    monthlyProfit: 1250000,
    monthlyPageviews: 35000,
    revenueMultiple: 7.2,
    profitMultiple: 4.3,
    netProfit: 15000000,
    revenue: 18960000,
    image: "/service.png",
  },
  {
    id: 14,
    title: "Starter E-commerce Store",
    description: "New e-commerce store in the beauty niche with professional design and initial inventory included.",
    price: 5000,
    niche: "E-commerce",
    revenueGenerating: false,
    location: "India",
    targetCountry: "United States",
    businessAge: 6,
    monthlyRevenue: 0,
    monthlyProfit: 0,
    monthlyPageviews: 1000,
    revenueMultiple: 0,
    profitMultiple: 0,
    netProfit: 0,
    revenue: 0,
    image: "/service.png",
  },
  {
    id: 15,
    title: "Starter Blog",
    description: "New blog in the finance niche with 20 articles and professional design, ready for monetization.",
    price: 800,
    niche: "Content",
    revenueGenerating: false,
    location: "United Kingdom",
    targetCountry: "Global",
    businessAge: 6,
    monthlyRevenue: 0,
    monthlyProfit: 0,
    monthlyPageviews: 2500,
    revenueMultiple: 0,
    profitMultiple: 0,
    netProfit: 0,
    revenue: 0,
    image: "/service.png",
  },
]



export const dummyTeamMembers = [
  {
    id: 1,
    title: "Actually managed Listings",
    number: "104",
    url: "#"
  },
  {
    id: 2,
    title: "Actually managed Chats",
    number: "208",
    url: "#"
  },
  {
    id: 3,
    title: "Activity Log",
    number: "1233",
    url: "#"
  },
]

export const dummyUserDetail = [
  {
    id: 1,
    title: "Users Listings",
    number: "6     ",
    url: "#"
  },
  {
    id: 2,
    title: "Users Favorite’s   ",
    number: "208",
    url: "#"
  },
  {
    id: 3,
    title: "Users Chats",
    number: "20",
    url: "#"
  },
]

export const businessData = [
    {
      fields: [
        { label: "What Is Your Background ?", value: "None of the Above" },
        { label: "Select Business Categories", value: "Market Place, Affiliate, Local " },
        { label: "What Is Your Niches ?", value: "Pet, Beauty, Others" },
      ],
    },
    {
      title: "Finance Data",
      fields: [
        { label: "Listing Price", value: "500$ - 5000$" },
        { label: "Seller Location", value: "United State" },
        { label: "Target Location", value: "United State" },
      ],
    },
    {
      fields: [
        { label: "Business Age", value: "6 - 15 Years" },
        { label: "Yearly Profit", value: "500$ - 5000$" },
        { label: "X Profit Multiple", value: "5x – 20x" },
        { label: "X Revenue Multiple", value: "5x – 20x" },
      ],
    },
  ]

export const Userlistings = [
  {
    title: "High Profitable! Pet Online Shop",
    image: "/service.png",
    category: "Ecommerce",
    status: "Draft",
    price: 105000,
    createdAt: "2025-03-30",
    requests: 0,
    alart: "Edit or Publish your Listing",
    managedBy: "EX",
    actions: ["Edit", "Publish"],
  },
  {
    title: "Premium Cosmetic Brand",
    image: "/service.png",
    category: "Ecommerce",
    status: "Published",
    price: 25000,
    createdAt: "2025-08-01",
    requests: 23,
    alart: "2 unanswered messages",
    actions: ["Push Listing", "View Requests"],
  },
  {
    title: "Fast Growing Software Startup",
    image: "/service.png",
    category: "Service Business",
    status: "Published",
    price: 2350000,
    createdAt: "2025-12-01",
    requests: 20,
    alart: "5 unanswered messages",
    actions: ["Push Listing", "View Requests"],
  },
  {
    title: "E-commerce Store",
    image: "/service.png",
    category: "Ecommerce",
    status: "Draft",
    price: 12000,
    createdAt: "2025-06-01",
    requests: 45, 
    actions: ["Push Listing", "View Requests"],
  },
  {
    title: "E-commerce Store",
    image: "/service.png",
    category: "Ecommerce",
    status: "Published",
    price: 12000,
    createdAt: "2025-06-01",
    requests: 45,
    actions: ["Push Listing", "View Requests"],
  },
  {
    title: "E-commerce Store",
    image: "/service.png",
    category: "Ecommerce",
    status: "Draft",
    price: 12000,
    createdAt: "2025-06-01",
    requests: 8,
    actions: ["View Old Requests"],
  },
];
 

// dummyChats.js

export const dummychats = [
  {
    id: 1,
    name: "John Doe",
    avatar: "/avatar1.png",
    isOnline: false,
    lastMessage: "1 min ago",
    lastSeen: "2h",
    unreadCount: 2,
    isVerified: true
  },
  {
    id: 2,
    name: "Sophia Smith",
    avatar: "/avatar1.png",
    isOnline: true,
    lastMessage: "2 min ago",
    lastSeen: "1h",
    unreadCount: 1,
    isVerified: false
  },
  {
    id: 3,
    name: "Emily Johnson",
    avatar: "/avatar1.png",
    isOnline: false,
    lastMessage: "5 min ago",
    lastSeen: "1h",
    unreadCount: 0,
    isVerified: true
  },
  {
    id: 4,
    name: "Online Fashion Store",
    avatar: "/avatar1.png",
    isOnline: true,
    lastMessage: "10 min ago",
    status: "Good",
    lastSeen: "1 min ago",
    unreadCount: 3,
    isVerified: true
  },
  {
    id: 5,
    name: "Emma Brown",
    avatar: "/avatar1.png",
    isOnline: true,
    lastMessage: "15 min ago",
    lastSeen: "5m",
    unreadCount: 1,
    isVerified: false
  },
  {
    id: 6,
    name: "Liam Wilson",
    avatar: "/avatar1.png",
    isOnline: false,
    lastMessage: "20 min ago",
    lastSeen: "2h",
    unreadCount: 0,
    isVerified: false
  },
  {
    id: 7,
    name: "Olivia Martinez",
    avatar: "/avatar1.png",
    isOnline: true,
    lastMessage: "1 day ago",
    lastSeen: "now",
    unreadCount: 0,
    isVerified: false
  },
  
];



export const dummyAdminListings  = [
  {
    userName: "NovaRidge",
    title: "Profitable Pet Shop",
    link: "www.pets.de",
    status: "EX by EX",
    created: "2025-07-10",
    managed: "by EX",
    responsible: "Add+",
    view: "..."
  },
  {
    userName: "UrbanValor",
    title: "500k Shopify Shop",
    link: "www.shopify.de",
    status: "Pending",
    created: "2025-07-10",
    managed: null,
    responsible: "Add+",
    view: "..."
  },
  {
    userName: "Skylenix",
    title: "Fashion Store",
    link: "www.fashion.de",
    status: "Published",
    created: "2025-07-09",
    managed: null,
    responsible: "Add+",
    view: "..."
  },
  {
    userName: "Westverra",
    title: "Marketing Agency",
    link: "www.marketing.de",
    status: "Published",
    created: "2025-07-09",
    managed: null,
    responsible: "Add+",
    view: "..."
  },
  {
    userName: "BoldCraft",
    title: "YouTube Account",
    link: "www.youtubee.de",
    status: "Published (Pro)",
    created: "2025-07-08",
    managed: null,
    responsible: "Add+",
    view: "..."
  },
  {
    userName: "NovaRidge",
    title: "Profitable Pet Shop",
    link: "www.pets.de",
    status: "Published",
    created: "2025-07-08",
    managed: null,
    responsible: "Add+",
    view: "..."
  },
  {
    userName: "UrbanValor",
    title: "500k Shopify Shop",
    link: "www.shopify.de",
    status: "Delisted",
    created: "2025-07-07",
    managed: null,
    responsible: "Add+",
    view: "..."
  },
  {
    userName: "Skylenix",
    title: "Fashion Store",
    link: "www.fashion.de",
    status: "Published",
    created: "2025-07-06",
    managed: null,
    responsible: "Add+",
    view: "..."
  },
  {
    userName: "Westverra",
    title: "Marketing Agency",
    link: "www.marketing.de",
    status: "Published",
    created: "2025-07-05",
    managed: null,
    responsible: "Add+",
    view: "..."
  },
  {
    userName: "BoldCraft",
    title: "YouTube Account",
    link: "www.youtubee.de",
    status: "Published",
    created: "2025-07-04",
    managed: null,
    responsible: "Add+",
    view: "..."
  }
];
