import { toast } from "sonner";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

/**
 * Where "Check Financing Options" sends the buyer.
 *
 * Empty on purpose. The design shows the button and says "complete the form
 * below", but there is no form in it and no partner named — and this platform
 * has no contact route to fall back on either: the support endpoint wants a
 * chat room, and no support address is configured anywhere.
 *
 * So rather than invent a destination, the button acknowledges the buyer and
 * this constant waits for the real one. Set it to the partner's URL and the
 * button becomes a link; nothing else here has to change.
 */
const FINANCING_ENQUIRY_URL = "";

/**
 * What financing on this platform means, said before a buyer is asked to
 * pursue it.
 *
 * Opened from the "Financing" link beside the instalment figure — a link that
 * until now pointed at "#", so the one question a buyer is most likely to have
 * about a price they cannot pay outright had no answer anywhere.
 */
export const FinancingDialog = ({
  open,
  onOpenChange,
  listingName,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  /** Named in the enquiry, so the team knows which business is meant. */
  listingName?: string;
}) => {
  const handleCheck = () => {
    if (FINANCING_ENQUIRY_URL) {
      window.open(FINANCING_ENQUIRY_URL, "_blank", "noopener,noreferrer");
      onOpenChange(false);
      return;
    }

    toast.success(
      listingName
        ? `Thanks — we will be in touch about financing for ${listingName}.`
        : "Thanks — we will be in touch about financing options.",
    );
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-[420px] rounded-2xl p-6">
        <DialogHeader className="space-y-0">
          <DialogTitle
            className="text-left text-[15px] font-semibold text-[#0F172A]"
            style={{ fontFamily: "Lufga" }}
          >
            Want to Finance This Business?
          </DialogTitle>
        </DialogHeader>

        <div
          className="space-y-3 text-[11.5px] leading-relaxed text-[#64748B]"
          style={{ fontFamily: "Lufga" }}
        >
          <p className="m-0">
            Explore financing solutions through our trusted global banking and lending
            partners.
          </p>
          <p className="m-0">
            We work with banks and financing institutions worldwide to help buyers access
            flexible financing options and simplify the acquisition process.
          </p>
          <p className="m-0">
            Bank loans can be a practical solution because repayments may often be covered
            through the monthly profit generated by the business.
          </p>
          <p className="m-0">
            If you would like to know whether a bank loan could work for your target
            business, please complete the form below.
          </p>
        </div>

        <button
          type="button"
          onClick={handleCheck}
          className="mt-1 w-full rounded-full py-3 text-[13px] font-medium text-black transition-opacity hover:brightness-95"
          style={{ background: "rgba(197, 253, 31, 1)", fontFamily: "Lufga" }}
        >
          Check Financing Options
        </button>

        <p
          className="m-0 text-center text-[10px] leading-relaxed text-[#94A3B8]"
          style={{ fontFamily: "Lufga" }}
        >
          Financing is arranged by independent third-party lenders. Approval and terms are
          decided by the lender, not by this platform.
        </p>
      </DialogContent>
    </Dialog>
  );
};

export default FinancingDialog;
